config/routes.rb
Eigtheen::Application.routes.draw do
  resources :ages
  root :to => 'ages#index'

end

app/models/age.rb
class Age < ActiveRecord::Base
  attr_accessible :answer, :question
end

app/controllers/ages_controller.rb
class AgesController < ApplicationController
  # GET /ages
  # GET /ages.json
  def index
    @ages = Age.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ages }
    end
  end

  # GET /ages/1
  # GET /ages/1.json
  def show
    @age = Age.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @age }
    end
  end

  # GET /ages/new
  # GET /ages/new.json
  def new
    @age = Age.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @age }
    end
  end

  # GET /ages/1/edit
  def edit
    @age = Age.find(params[:id])
  end

  # POST /ages
  # POST /ages.json
  def create
    @age = Age.new(params[:age])

    respond_to do |format|
      if @age.save
        format.html { redirect_to @age, notice: 'Age was successfully created.' }
        format.json { render json: @age, status: :created, location: @age }
      else
        format.html { render action: "new" }
        format.json { render json: @age.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ages/1
  # PUT /ages/1.json
  def update
    @age = Age.find(params[:id])

    respond_to do |format|
      if @age.update_attributes(params[:age])
        format.html { redirect_to @age, notice: 'Age was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @age.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ages/1
  # DELETE /ages/1.json
  def destroy
    @age = Age.find(params[:id])
    @age.destroy

    respond_to do |format|
      format.html { redirect_to ages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/ages_helper.rb
module AgesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ages/_form.html.erb
<%= form_for(@age) do |f| %>
  <% if @age.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@age.errors.count, "error") %> prohibited this age from being saved:</h2>

      <ul>
      <% @age.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
      <%= f.label :question %><br />
      <%= f.text_field :question %>
    </div> -->
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </div>
  <div class="actions">
    <%= f.submit "Submit"%>
  </div>
<% end %>

app/views/ages/edit.html.erb
<h1>Editing age</h1>

<%= render 'form' %>

<%= link_to 'Show', @age %> |
<%= link_to 'Back', ages_path %>

app/views/ages/index.html.erb
<!-- <h1>Listing ages</h1> -->
<h1><%= link_to 'What Would You Do If You Were 18 Again?', new_age_path %></h1>

<table>
  <tr>
        <!-- <th>Question</th> -->
        <th>Answer</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

<% @ages.each do |age| %>
<ol>
  <tr>
    <td><%= age.question %></td>
    <td><%= age.answer %></td>
    <td><%= link_to 'Show', age %></td>
    <td><%= link_to 'Edit', edit_age_path(age) %></td>
    <td><%= link_to 'Destroy', age, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<!-- <%= link_to 'New Age', new_age_path %> -->

app/views/ages/new.html.erb
<h1>What would you do if you were 18 again</h1>

<%= render 'form' %>

<%= link_to 'Back', ages_path %>

app/views/ages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @age.question %>
</p>

<p>
  <b>Answer:</b>
  <%= @age.answer %>
</p>


<%= link_to 'Edit', edit_age_path(@age) %> |
<%= link_to 'Back', ages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eigtheen</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>